---
  - name: Preparation | Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Installation | Install mysql and all required packages
    apt: name={{ item }} state=present
    with_items:
      - python-mysqldb
      - mysql-server

  - name: Installation | Ensure that the service is running
    service: name=mysql state=started enabled=true

  - name: Installation | update mysql root password for all root accounts
    mysql_user: name={{ db_user }} host=localhost password={{ db_password }}

  - name: Installation | copy .my.cnf file with root password credentials
    template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: Installation | update mysql root password for all root accounts
    mysql_user: name={{ db_user }} host={{ item }} password={{ db_password }} priv="*.*:ALL,GRANT"
    with_items:
      - "%"
    notify:
      - restart mysql

  - name: Installation | ensure anonymous users are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost
      - "{{ inventory_hostname }}"

  - name: Installation | remove the test database
    mysql_db: name=test state=absent

  - name: Installation | Setup bind address
    lineinfile: regexp='\s*bind-address.*' line='bind-address=0.0.0.0' dest=/etc/mysql/my.cnf
    notify:
      - restart mysql

  - name: Installation | Setup max connections
    lineinfile: regexp='\s*max_connections.*' line='max_connections = 500' dest=/etc/mysql/my.cnf
    notify:
      - restart mysql
